name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
  release:
    types: [published]

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release info
        id: release_info
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "::set-output name=version::${{ github.event.inputs.version }}"
            echo "::set-output name=url::https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.event.inputs.version }}.tar.gz"
          else
            echo "::set-output name=version::$(echo ${{ github.ref }} | cut -d '/' -f3)"
            echo "::set-output name=url::https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.ref }}.tar.gz"
          fi

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(curl -sL "${{ steps.release_info.outputs.url }}" | shasum -a 256 | awk '{ print $1 }')
          echo "::set-output name=sha256::$SHA256"

      - name: Set up Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential procps curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew --version

      - name: Update Homebrew formula
        run: |
          brew install yq
          yq -i '.version = "${{ steps.release_info.outputs.version }}"' hiramu-cli.rb
          yq -i '.sha256 = "${{ steps.sha256.outputs.sha256 }}"' hiramu-cli.rb

      - name: Test Homebrew formula
        run: |
          brew install --build-from-source ./hiramu-cli.rb
          hiramu-cli --version

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add hiramu-cli.rb
          git commit -m "Update Homebrew formula for version ${{ steps.release_info.outputs.version }}"
          git push